name: Sync To Gitee

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/GC-ZF
          dst: gitee/gc-zhang
          dst_key: ${{ secrets.GC_Zhang }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "TG-Learn"