name: Sync To Gitee

on: # 触发条件
  push:
    branches:
      - main # 推送到 main 分支

  release:
    types:
      - published # 推送新版本号

  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:GC-ZF/TG-Learn.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gc-zhang/TG-Learn.git
